version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Models:/app/Models
      - ./app:/app/app
    depends_on:
      - frontend
    environment:
      MY_ENV_VAR_1: "value1"
      MY_ENV_VAR_2: "value2"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./Frontend/my-angular-app
      dockerfile: Dockerfile
    ports:
      - "4500:80"
    volumes:
      - ./Frontend/my-angular-app:/usr/share/nginx/html
      - ./Frontend/my-angular-app/dist:/usr/share/nginx/html  # Ensure this points to your build folder

    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

